# Generated by Django 5.1.6 on 2025-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lastfm_listeners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lastfm_playcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lastfm_tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='song',
            name='lastfm_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lastfm_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
