# Generated by Django 5.1.6 on 2025-04-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
    ]
