# Generated by Django 5.1.6 on 2025-06-08 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('spotify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SpotifyPlaylistImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_playlist_id', models.CharField(max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('local_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'spotify_playlist_id')},
            },
        ),
    ]
