# Generated by Django 5.1.6 on 2026-04-07 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_lastfm_listeners_song_lastfm_playcount_and_more'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='music.playlist'),
        ),
    ]
