# Generated by Django 5.1.6 on 2025-06-07 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added to playlist'), ('played', 'Played'), ('skipped', 'Skipped'), ('liked', 'Liked'), ('disliked', 'Disliked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='playlistrecommendation',
            options={'ordering': ['-score', '-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='playlistrecommendation',
            name='recommendat_playlis_8680c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='playlistrecommendation',
            name='recommendat_song_id_4b9b73_idx',
        ),
        migrations.AlterUniqueTogether(
            name='playlistrecommendation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playlistrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content', 'Content-Based'), ('hybrid', 'Hybrid')], default='hybrid', max_length=50),
        ),
        migrations.AlterField(
            model_name='hybridrecommendation',
            name='strategy',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('discovery', 'Discovery'), ('similarity', 'Similarity-focused'), ('popular', 'Popular')], default='balanced', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='playlistrecommendation',
            unique_together={('playlist', 'song', 'recommendation_type')},
        ),
        migrations.AddIndex(
            model_name='playlistrecommendation',
            index=models.Index(fields=['playlist', '-score'], name='recommendat_playlis_8c06b1_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistrecommendation',
            index=models.Index(fields=['updated_at'], name='recommendat_updated_662f3c_idx'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.playlistrecommendation'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recommendationfeedback',
            unique_together={('user', 'recommendation', 'action')},
        ),
    ]
